-- type
-- 문자 : varchar, char, text, CLOB(Characcter Large OBject)
-- 정수 : medium int, int(signed, integer), unsigned, big int 
-- 실수 : float, double
-- 시간 : date, datetime
-- LOB : CLOB, BLOB(Binary Large OBject)
